- name: Install docker-compose
  become: true
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'
    owner: vagrant
    group: vagrant
